/* criar um banco de dados para um projeto de oficina

Cadastro de carros, serviço e dono

cliente -> 1 carro apenas
Carro -> 1 marca
Cores dos carros -> N cores (muitas)

Clientes informam telefone mas não obrigatório*/

CREATE DATABASE MECANICA;

USE MECANICA;

/* COLOCAR IDSERVICO PRIMARY KEY AUTO_INCREMENT E POSSUI RELACIONAMENTO COM CLIENTES FOREIGN KEY CLIENTES (IDCLIENTES) */

CREATE TABLE SERVICO(
TP_SERVICO VARCHAR (50),
VALOR FLOAT (100, 2)
);

/* COLOCAR IDCARRO PRIMARY KEY AUTO_INCREMENT E POSSUI RELACIONAMENTO COM CLIENTES FOREIGN KEY CLIENTES (IDCLIENTES)*/

CREATE TABLE CARROS(
MARCA VARCHAR (50) NOT NULL,
MODELO VARCHAR (50),
PLACA VARCHAR (10) NOT NULL
);

/* COLOCAR IDCLIENTE PRIMARY KEY AUTO_INCREMENT E POSSUI RELACIONAMENTO COM CARROS E SERVICO */
CREATE TABLE CLIENTES(
NOME VARCHAR (50) NOT NULL,
TELEFONE VARCHAR (12)
);

/* COLOCAR IDCARRO PRIMARY KEY AUTO_INCREMENT E POSSUI RELACIONAMENTO COM CARRO FOREIGN KEY CLIENTES (IDCARRO) */
CREATE TABLE CORES( NOME_COR VARCHAR (30) );

/* ADICIONANDO COLUNA ID E COLOCANDO PRIMARY KEY*/

/* SERVICO */
ALTER TABLE SERVICO
ADD IDSERVICO INT

ALTER TABLE SERVICO ADD CONSTRAINT PK_SERVICO
PRIMARY KEY (IDSERVICO);

/* CARRO */
ALTER TABLE CARROS
ADD IDCARROS INT

ALTER TABLE CARRO ADD CONSTRAINT PK_CARRO
PRIMARY KEY (IDCARRO);

/*CLIENTE*/

ALTER TABLE CLIENTES
ADD IDCLIENTE INT,
ADD ID_SERVICO INT,
ADD ID_CARRO INT;


ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY(IDCLIENTE);


ALTER TABLE CLIENTES 
ADD CONSTRAINT FK_CLIENTE_SERVICO
FOREIGN KEY(ID_SERVICO)
REFERENCES SERVICO(IDSERVICO);


ALTER TABLE CLIENTES 
ADD CONSTRAINT FK_CLIENTE_CARRO
FOREIGN KEY(ID_CARRO)
REFERENCES CARROS(IDCARROS);

/* CORES */

ALTER TABLE CORES
ADD IDCORES INT;

ALTER TABLE CORES ADD CONSTRAINT PK_CORES
PRIMARY KEY (IDCORES);