/*CRIANDO DATABASE E TABELA*/
CREATE DATABASE LIVRARIA;
USE LIVRARIA;
CREATE TABLE LIVROS2(
	NOME_DO_LIVRO VARCHAR (50),
    NOME_DO_AUTOR VARCHAR (50),
    SEXO_DO_AUTOR CHAR (10),
    NUMERO_DE_PAGINAS INT (10),
    NOME_DA_EDITORA VARCHAR (50),
    VALOR_DO_LIVRO NUMERIC (4),
    ESTADO_UF_DA_EDITORA CHAR(2),
    ANO_PUBLICADO CHAR(4)
    );

/*INSERINDO DADOS*/
INSERT INTO LIVROS (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_UF_DA_EDITORA, ANO_PUBLICADO) VALUES
('Cavaleiro Real','Ana Claudia', 'Feminino', 465, 'Atlas',49.9,	'RJ', 2009);
INSERT INTO LIVROS (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_UF_DA_EDITORA, ANO_PUBLICADO) VALUES
('Pessoas Efetivas', 'Eduardo Santos',	'Masculino',	390,	'Beta',	78.99,	'RJ',	2018);
INSERT INTO LIVROS (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO_DO_AUTOR, NUMERO_DE_PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, ESTADO_UF_DA_EDITORA, ANO_PUBLICADO) VALUES
('SQL para leigos', 'João Nunes', 'Masculino', 450, 'Addison', 98, 'SP',2018),
('Receitas Caseiras',	'Celia Tavares',	'Feminino',	210,	'Atlas',	45,	'RJ',	2008),
('Habitos Saudáveis',	'Eduardo Santos',	'Masculino',	630,	'Beta',	150.98,	'RJ',	2019),
('A Casa Marrom	Hermes', 'Macedo',	'Masculino',	250,	'Bubba',	60,	'MG',	2016),
('Estacio Querido',	'Geraldo Francisco',	'Masculino',	310,	'Insignia',	100,	'ES',	2015),
('Pra sempre amigas',	'Leda Silva',	'Feminino',	510,	'Insignia',	78.98,	'ES',	2011),
('Copas Inesqueciveis',	'Marco Alcantara',	'Masculino',	200,	'Larson',	130.98,	'RS',	2018),
('O poder da mente',	'Clara Mafra',	'Feminino',	120,	'Continental',	56.58,	'SP',	2017);

/* Trazer todos os dados*/
SELECT * FROM LIVROS;

/* Traz o nome da editora e livro*/
SELECT NOME_DO_LIVRO, NOME_DO_AUTOR FROM LIVROS;

/* TRAZ O NOME DO LIVRO E UF DOS AUTORES DOS SEXOS MASCULINOS*/
SELECT NOME_DO_LIVRO, ESTADO_UF_DA_EDITORA FROM LIVROS
WHERE SEXO_DO_AUTOR = 'MASCULINO';

/* TRAZ O NOME DO LIVRO E NUMERO DE PAGINAS DOS AUTORES DOS SEXOS FEMININOS*/
SELECT NOME_DO_LIVRO, NUMERO_DE_PAGINAS FROM LIVROS
WHERE SEXO_DO_AUTOR = 'FEMININO';

/* TRAZ OS VALORES DOS LIVROS DAS EDITORAS DE SP*/
SELECT VALOR_DO_LIVRO FROM LIVROS
WHERE ESTADO_UF_DA_EDITORA = 'SP';

/*TRAZ os dados dos autores do sexo masculino que tiveram livros publicados por São Paulo ou Rio de Janeiro */
SELECT NOME_DO_AUTOR, SEXO_DO_AUTOR FROM LIVROS
WHERE SEXO_DO_AUTOR = 'MASCULINO'
AND(ESTADO_UF_DA_EDITORA = 'SP' OR ESTADO_UF_DA_EDITORA ='RJ'); 

SELECT SEXO_DO_AUTOR, COUNT(*)
FROM LIVROS
GROUP BY SEXO_DO_AUTOR;

SELECT * FROM LIVROS;

USE PROJETO;
SHOW TABLES;
SELECT * FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = 'LILIAN@HOTMAIL.COM';

USE LIVRARIA;
SELECT * FROM LIVROS;

UPDATE LIVROS
SET VALOR_DO_LIVRO = 49.9
WHERE VALOR_DO_LIVRO = 50;